import {router} from 'expo-router';
import {LinearGradient} from 'expo-linear-gradient';
import {Pressable,StyleSheet,Text,View,ScrollView} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAppProgress} from './_layout';
import {StarBadge} from './components';
const cats=[['animals','חיות','🦁'],['numbers','מספרים','123'],['letters','אותיות','אבג'],['colors','צבעים וצורות','🔴🟨'],['puzzles','פאזלים','🧩'],['memory','זיכרון','🃏'],['math','חשבון','➕'],['draw','ציור וצביעה','🎨'],['differences','מצא את ההבדלים','🔍'],['mazes','מבוכים','🌀'],['music','מוזיקה וקצב','🎵'],['sorting','מיון והתאמה','🧺']];
export default function Categories(){const {stars}=useAppProgress();return <SafeAreaView style={s.safe}><LinearGradient colors={['#36b9ed','#c6eff5','#f2f5c5']} style={s.bg}><ScrollView contentContainerStyle={s.page}><View style={s.head}><Pressable onPress={()=>router.back()}><Text style={s.back}>←</Text></Pressable><Text style={s.title}>בחר קטגוריה</Text><View style={s.star}><Text>⭐ {stars}</Text></View></View><View style={s.grid}>{cats.map(([id,t,i])=><Pressable key={id} onPress={()=>router.push(id === 'animals' ? '/game/animals' : `/game/${id}`)} style={s.card}><LinearGradient colors={['#fff','#eef8ff']} style={s.cardIn}><Text style={s.icon}>{i}</Text><Text style={s.cardText}>{t}</Text></LinearGradient></Pressable>)}</View><Pressable style={s.adventure} onPress={()=>router.push('/adventure')}><Text style={{fontSize:38}}>🗺️</Text><View><Text style={s.adTitle}>מסע ההרפתקה</Text><Text style={s.adText}>צאו למסע בעולם של משחקים!</Text></View><Text style={{fontSize:40}}>🦁</Text></Pressable></ScrollView></LinearGradient></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1},bg:{flex:1},page:{padding:10,paddingBottom:25},head:{height:70,flexDirection:'row',alignItems:'center',gap:14},back:{fontSize:34,fontWeight:'900',color:'#2877a0'},title:{flex:1,textAlign:'center',fontSize:27,fontWeight:'900',color:'#fff',textShadowColor:'#387b9d',textShadowOffset:{width:1,height:2},textShadowRadius:2},star:{backgroundColor:'#fff6d8',borderRadius:18,padding:9,fontWeight:'900'},grid:{flexDirection:'row',flexWrap:'wrap',gap:9,justifyContent:'center'},card:{width:'30%',minWidth:105,aspectRatio:1,borderRadius:19,overflow:'hidden',borderWidth:2,borderColor:'#fff',elevation:3},cardIn:{flex:1,alignItems:'center',justifyContent:'center'},icon:{fontSize:36,fontWeight:'900',color:'#d26c55'},cardText:{fontSize:14,fontWeight:'900',color:'#5a4a45',textAlign:'center',marginTop:5},adventure:{marginTop:14,minHeight:80,borderRadius:22,backgroundColor:'#f3a923',borderWidth:3,borderColor:'#fff',padding:8,flexDirection:'row',alignItems:'center',justifyContent:'space-around'},adTitle:{fontSize:22,fontWeight:'900',color:'#fff'},adText:{fontSize:12,color:'#fff',fontWeight:'700'}});
