import { Image, Pressable, StyleSheet, Text, View, useWindowDimensions, ScrollView } from 'react-native';
import { router } from 'expo-router';
import { useAppProgress } from './_layout';
import { createReferenceLayout } from '../src/ui/layout';
const W=403,H=493;
const avatars:Record<string,any>={lion:require('../assets/avatar-lion.png'),rabbit:require('../assets/avatar-rabbit.png'),elephant:require('../assets/avatar-elephant.png'),panda:require('../assets/avatar-panda.png'),monkey:require('../assets/avatar-monkey.png'),giraffe:require('../assets/avatar-giraffe.png'),fox:require('../assets/avatar-fox.png'),penguin:require('../assets/avatar-penguin.png'),bear:require('../assets/avatar-bear.png')};
export default function ProfilesMore(){
  const{width,height}=useWindowDimensions();const layout=createReferenceLayout(W,H,width,height);const{profiles,selectProfile,selectedProfileId}=useAppProgress();
  return <View style={s.root}>
    <View pointerEvents="none" style={{position:'absolute',left:layout.offsetX,top:layout.offsetY,width:layout.canvasWidth,height:layout.canvasHeight}}><Image source={require('../assets/profiles-reference-clean.png')} style={StyleSheet.absoluteFillObject} resizeMode="cover"/></View>
    <Text style={[s.title,{top:74*layout.scale+layout.offsetY,fontSize:24*layout.scale}]}>כל הפרופילים</Text>
    <ScrollView contentContainerStyle={{paddingTop:120*layout.scale+Math.max(0,layout.offsetY),paddingBottom:40*layout.scale,paddingHorizontal:8}}>
      <View style={s.grid}>{profiles.map(p=><Pressable key={p.id} style={[s.card,{width:113*layout.scale,height:184*layout.scale}]} onPress={async()=>{await selectProfile(p.id);router.replace('/home')}}><View style={{position:'relative',width:82*layout.scale,height:82*layout.scale,marginTop:10*layout.scale}}><Image source={avatars[p.avatar]||avatars.lion} style={{width:'100%',height:'100%'}}/>{selectedProfileId===p.id&&<Image source={require('../assets/selected-check.png')} style={{position:'absolute',right:-4*layout.scale,top:-4*layout.scale,width:26*layout.scale,height:26*layout.scale}} resizeMode="contain"/>}</View><Text style={[s.name,{fontSize:17*layout.scale}]}>{p.name}</Text><View style={{width:76*layout.scale,height:28*layout.scale,marginTop:8*layout.scale}}><Image source={require('../assets/star-badge-base.png')} style={StyleSheet.absoluteFillObject} resizeMode="cover"/><Text style={[s.stars,{fontSize:14*layout.scale}]}>{p.stars}</Text></View></Pressable>)}</View>{profiles.length<6 ? <Pressable style={[s.add,{width:190*layout.scale,height:72*layout.scale}]} onPress={()=>router.push('/create-profile')}><Text style={[s.plus,{fontSize:28*layout.scale}]}>＋</Text><Text style={[s.addText,{fontSize:17*layout.scale}]}>ילד/ה חדש/ה</Text></Pressable> : <Text style={[s.full,{fontSize:16*layout.scale}]}>הגעתם למספר הפרופילים המקסימלי</Text>}</ScrollView>
    <Pressable style={{position:'absolute',left:14*layout.scale+layout.offsetX,top:14*layout.scale+layout.offsetY,width:48*layout.scale,height:48*layout.scale}} onPress={()=>router.replace('/profiles')} />
  </View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#dff5ff'},title:{position:'absolute',left:0,width:'100%',textAlign:'center',fontWeight:'900',color:'#5b3a9e'},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:12},card:{backgroundColor:'rgba(255,255,255,.82)',borderRadius:18,alignItems:'center',marginBottom:14,overflow:'hidden',borderWidth:2,borderColor:'#d8d1ee'},name:{fontWeight:'900',color:'#5141a5',marginTop:5},stars:{textAlign:'center',fontWeight:'900',color:'#7b633b',marginTop:4},add:{alignSelf:'center',backgroundColor:'#9b55cf',borderRadius:20,alignItems:'center',justifyContent:'center',marginTop:8},plus:{color:'#fff',fontWeight:'900',lineHeight:32},full:{textAlign:'center',color:'#5b3a9e',fontWeight:'900',marginTop:18},addText:{color:'#fff',fontWeight:'900'}});
