import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useAppProgress } from './_layout';
const rows=[['animals','חיות','animals','icon-animals.png'],['numbers','מספרים','numbers','icon-numbers.png'],['letters','אותיות','letters','icon-letters.png'],['memory','זיכרון','memory','icon-memory.png'],['draw','ציור','draw','icon-draw.png']] as const;
const icons:any={animals:require('../assets/icon-animals.png'),numbers:require('../assets/icon-numbers.png'),letters:require('../assets/icon-letters.png'),memory:require('../assets/icon-memory.png'),draw:require('../assets/icon-draw.png')};
export default function Report(){const{stars,gamesPlayed,completed}=useAppProgress();return <View style={s.root}>
 <View style={s.sky}/><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable>
 <View style={s.titlePlate}><Text style={s.title}>הדוח שלי</Text></View>
 <View style={s.summary}><Box v={stars} t="כוכבים"/><Box v={gamesPlayed} t="משחקים"/><Box v={completed.size} t="הושלמו"/></View>
 <View style={s.card}>{rows.map(([id,t])=><View key={id} style={s.row}><Image source={icons[id]} resizeMode="contain" style={s.icon}/><View style={s.rowInfo}><Text style={s.label}>{t}</Text><View style={s.track}><View style={[s.fill,{width:completed.has(id)?'100%':'18%'}]}/></View></View><Text style={[s.status,{color:completed.has(id)?'#63a92d':'#84939a'}]}>{completed.has(id)?'הושלם':'בתהליך'}</Text></View>)}</View>
 <View style={s.note}><Text style={s.noteTitle}>התקדמות כללית</Text><Text style={s.noteText}>{completed.size} מתוך 5 קטגוריות מרכזיות הושלמו</Text></View>
 </View>}
function Box({v,t}:{v:number;t:string}){return <View style={s.box}><Text style={s.value}>{v}</Text><Text style={s.sub}>{t}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#e0f6ff',padding:16,alignItems:'center'},sky:{...StyleSheet.absoluteFillObject,backgroundColor:'#e0f6ff'},back:{position:'absolute',top:14,left:12,width:46,height:46,borderRadius:16,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',zIndex:10},backText:{fontSize:38,fontWeight:'900',color:'#477b92',marginTop:-4},titlePlate:{marginTop:8,backgroundColor:'#6bb92c',borderRadius:24,paddingHorizontal:38,paddingVertical:10,borderWidth:4,borderColor:'#fff'},title:{fontSize:28,fontWeight:'900',color:'#fff'},summary:{width:'96%',maxWidth:520,flexDirection:'row',gap:10,marginTop:18},box:{flex:1,backgroundColor:'#fff',borderRadius:20,padding:12,alignItems:'center',borderWidth:2,borderColor:'#e7dcc6'},value:{fontSize:28,fontWeight:'900',color:'#65a72c'},sub:{color:'#7d8b90',marginTop:4,fontWeight:'800'},card:{width:'96%',maxWidth:520,marginTop:14,backgroundColor:'#fff',borderRadius:24,padding:8,borderWidth:2,borderColor:'#e7dcc6'},row:{flexDirection:'row',alignItems:'center',padding:10,borderBottomWidth:1,borderBottomColor:'#edf0ef'},icon:{width:48,height:42},rowInfo:{flex:1,marginHorizontal:8},label:{fontSize:18,fontWeight:'900',color:'#42545c'},track:{height:8,backgroundColor:'#edf1f1',borderRadius:6,overflow:'hidden',marginTop:5},fill:{height:'100%',backgroundColor:'#7ac632'},status:{fontWeight:'900',fontSize:13},note:{width:'96%',maxWidth:520,marginTop:14,backgroundColor:'#fff7d9',borderRadius:20,padding:14,borderWidth:2,borderColor:'#e8cf7c'},noteTitle:{fontSize:18,fontWeight:'900',color:'#5b594d'},noteText:{fontSize:14,fontWeight:'700',color:'#77766d',marginTop:3}});
